select_origin: directory
files_origin: ./fiches
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#005C53"
    stroke: "#005C53"
  litterature: 
    fill: "#DBF227"
    stroke: "#DBF227"
  test: 
    fill: "#D6D58E"
    stroke: "#D6D58E"
  Concept:
    fill: "#042940"
    stroke: "#042940"
  perso:
    fill: "#005C53"
    stroke: "#005C53"
  references:
    stroke: "#6C6C6C"
    fill: "#6C6C6C"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: ""
author: ""
description: ""
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: en
